# Generated by Django 2.1.15 on 2020-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('appart_type', models.CharField(choices=[('ST', 'Studio'), ('T1', 'Appart T1'), ('T2', 'Appart T2'), ('T3', 'Appart T3'), ('T4', 'Appart T4')], max_length=2)),
                ('space', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
